Update build_ubuntu.yml

diff --git a/.github/workflows/build_ubuntu.yml b/.github/workflows/build_ubuntu.yml
--- a/.github/workflows/build_ubuntu.yml
+++ b/.github/workflows/build_ubuntu.yml
@@ -11,7 +11,9 @@ jobs:
         uses: actions/checkout@v3
 
       - name: Install dependencies
-        run: sudo apt update && sudo apt install -y cmake gcc libcjson-dev
+        run: |
+          sudo apt update && sudo apt install -y cmake gcc libcjson-dev
+          dpkg -L libcjson-dev | grep cJSON.h || (echo "cJSON header not found!" && exit 1)
 
       - name: Create build directory
         run: mkdir -p build
